---
abstract: 'creates a partial CPAN mirror for tests'
author:
  - 'Kenichi Ishigaki <ishigaki@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WorePAN
no_index:
  directory:
    - t
    - inc
requires:
  Archive::Any::Lite: 0.06
  Archive::Tar: 1.86
  CPAN::DistnameInfo: 0
  CPAN::Meta::YAML: 0
  File::Temp: 0
  IO::Zlib: 0
  JSON: 0
  LWP::Simple: 0
  Parse::CPAN::Whois: 0
  Parse::PMFile: 0.06
  Path::Extended: 0
  Test::More: 0.88
  Test::UseAllModules: 0.10
  URI: 0
  URI::QueryParam: 0
  version: 0
resources:
  repository: https://github.com/charsbar/worepan
version: 0.08
